DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE url_checks (
    id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE NOT NULL,
    url_id BIGINT NOT NULL,
    statusCode BIGINT,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (url_id) REFERENCES urls (id)
);